# -*- coding: utf-8 -*-
"""1_ML_First.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1M3tTaeDTzjRFVf5xnS0zQ5Dowl2v56vT

# **Machine Learning**
- Tensorflow: 머신러닝
- Keras: 딥러닝
- Pytorch
"""

print('Hello World')

import tensorflow
tensorflow.__version__

!pip list #!가 붙으면 cmd 통함

!pip uninstall tensorflow
!pip install tensorflow==1.15 #설치 후 런타임 다시 시작할 것

import tensorflow as tf

tf.__version__

import tensorflow as tf

import matplotlib.pyplot as plt

x = [1, 2, 3]
y = [1, 2, 3]

w = tf.placeholder(tf.float32)
hypothesis = x * w

cost = tf.reduce_mean(tf.square(hypothesis - y)) #오차 제곱의 평균

