# -*- coding: utf-8 -*-
"""8_MNIST_CNN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18ZX1vMri09s9pEvsKtgoRwYQme7cYFre
"""

#구글에서 제공하는 GPU를 이용해서 계산하기
!pip install tensorflow-gpu==2.2.0

# 패키지 불러오기

from keras.utils import to_categorical
from keras.datasets import mnist # (28 x 28 그림 데이터) : 
from keras.models import Sequential
from keras.layers import Dense, Conv2D, MaxPool2D, Flatten, Dropout

import numpy as np

# 이미지의 폭과 너비를 지정한 변수
width = 28
height = 28

# 데이터 로드하기
(X_train, y_train), (X_test, y_test) = mnist.load_data()

X_train.shape, y_train.shape, X_test.shape, y_test.shape

X_train[0]

y_train[0]

import matplotlib.pyplot as plt

plt.imshow(X_train[1]) # 이미지 찍어주기
plt.title("Correct : " + str(y_test[1]))
plt.show() # 화면에 출력하기

# 데이터를 스케일링 + 리쉐이프 + 타입 변환
X_train = X_train.reshape(60000, width, height, 1).astype('float32') / 255.0
X_test = X_test.reshape(10000, width, height, 1).astype('float32') / 255.0

# y값 onehot encoding
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)
y_train[0]

# 모델 만들기 : 미완성
# CNN (컨벌루셔널 뉴럴 네트워크 : Convolutional Neural Network)
model = Sequential()

model.add(Conv2D(32, (3, 3), activation="relu", input_shape=(width, height, 1)))  #흑백은 1, 컬러는 3
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Conv2D(32, (3, 3), activation="relu", input_shape=(width, height, 1)))  #흑백은 1, 컬러는 3
model.add(Conv2D(32, (3, 3), activation="relu"))
model.add(MaxPool2D(pool_size=(2, 2)))
model.add(Dropout(0.25))

model.add(Flatten()) # 이 작업이 끝나면 
model.add(Dense(256, activation="relu")) 

model.add(Dense(10, activation="softmax"))

model.compile(optimizer='sgd', loss='categorical_crossentropy', metrics=['accuracy'])

hist = model.fit(X_train, y_train, epochs=30, batch_size=32, validation_data= (X_test, y_test), verbose=1)

# 학습 과정을 그래프로 그려보기

import matplotlib.pyplot as plt

fig, loss_ax = plt.subplots()
acc_ax = loss_ax.twinx()

loss_ax.plot(hist.history['loss'], 'y', label = 'train loss')
loss_ax.plot(hist.history['val_loss'], 'r', label = 'val loss')

acc_ax.plot(hist.history['accuracy'], 'b', label = 'train acc')
acc_ax.plot(hist.history['val_accuracy'], 'g', label = 'val acc')

loss_ax.set_xlabel('Epoch')
loss_ax.set_ylabel('Loss')

acc_ax.set_ylabel('Accuracy')

loss_ax.legend(loc='upper left')
acc_ax.legend(loc='lower left')

plt.show()

yhat = model.predict(X_test, batch_size=32)

# 잘못 예측한 데이터 확인

import matplotlib.pyplot as plt

plt.rcParams["figure.figsize"] = (10, 10)
row = 5
col = 5

f, axarr = plt.subplots(row, col)
cnt = 0
i = 0

while cnt < (row * col) :
  if np.argmax(y_test[i] == yhat[i]):
    i = i + 1
    continue
  
  #답을 못 맞추었으므로 그림을 그려봄
  sub_plot = axarr[(int(cnt/row), int(cnt%col))]
  sub_plot.imshow(X_test[i].reshape(width, height))
  tmp = "C : " + str(np.argmax(y_test[i])) + ', P : ' + str(np.argmax(yhat[i]))
  sub_plot.set_title(tmp)

  i = i + 1
  cnt = cnt + 1

plt.show()

