# -*- coding: utf-8 -*-
"""3_Keras.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GE2PE8dbsMkZORDl1_Bw4P2bdn2AM6Qv
"""

from keras.models import Sequential
from keras.layers import Dense, Activation