# -*- coding: utf-8 -*-
"""12_Diabets.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wTo3izvmAOczGw-NDp2d3-ZBm1woJubb
"""

! pip install tensorflow-gpu==2.0.0

# 패키지 불러오기

from keras.models import Sequential
from keras.layers import Dense, Dropout
from sklearn.model_selection import train_test_split

import numpy as np
import pandas as pd

from google.colab import drive
drive.mount('/content/drive')

diabets = pd.read_csv('/content/drive/My Drive/data/datasets_diabetes.csv')
diabets

diabets.columns

# X, y 분리하기

X = diabets.iloc[:, 0:8].values # ndarray 2차원 (float64)
y = diabets.iloc[:, 8].values   # ndarray 1차원 (문자)

# 데이터 스케일링
X = X.astype('float32') / 255.0

# train, test 분리

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

X_train.shape, X_test.shape, y_train.shape, y_test.shape

# 모델 생성

model = Sequential()

model.add(Dense(32, activation='relu', input_shape=(8,)))
model.add(Dense(64, activation='relu'))
model.add(Dense(128, activation='relu'))
model.add(Dropout(0.25))
model.add(Dense(2, activation='softmax'))

model.summary()

model.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

hist = model.fit(X_train, y_train, epochs=1000, validation_data=(X_test, y_test))

